const router = require('express').Router();
const requireAuth = require('../middleware/auth');

// POST /api/auth/test-email — sends a plain test email to verify SMTP config
router.post('/test-email', requireAuth, async (req, res) => {
  const { to } = req.body;
  if (!to) return res.status(400).json({ error: 'to address required' });
  try {
    const nodemailer = require('nodemailer');
    const transporter = nodemailer.createTransport({
      host: 'smtp.gmail.com',
      port: 587,
      secure: false,
      auth: {
        user: process.env.EMAIL_USER,
        pass: (process.env.EMAIL_PASS || '').replace(/\s/g, ''),
      },
      tls: { rejectUnauthorized: false },
      connectionTimeout: 10000,
      greetingTimeout:   10000,
      socketTimeout:     15000,
    });
    await transporter.verify();
    await transporter.sendMail({
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to,
      subject: 'DIGIVET — SMTP test',
      text: 'If you received this, the email configuration is working correctly.',
    });
    res.json({ success: true, message: `Test email sent to ${to}` });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/auth/me
router.get('/me', requireAuth, (req, res) => {
  const { id, email, user_metadata } = req.user;
  res.json({
    id,
    email,
    role: user_metadata?.role ?? null,
    full_name: user_metadata?.full_name ?? null,
    owner_id: user_metadata?.owner_id ?? null,
  });
});

// Helper: query user_profile from local PostgreSQL (has all entries) with Supabase fallback
async function findUserProfile(normalizedEmail, supabase) {
  // Try local PostgreSQL first (has full data from local desktop system)
  if (process.env.LOCAL_DATABASE_URL) {
    try {
      const { Pool } = require('pg');
      const pool = new Pool({ connectionString: process.env.LOCAL_DATABASE_URL, connectionTimeoutMillis: 3000 });
      const { rows } = await pool.query(
        'SELECT id, display_name, role, local_email, local_password_hash FROM user_profile WHERE LOWER(local_email) = $1 LIMIT 1',
        [normalizedEmail]
      );
      await pool.end();
      if (rows.length > 0) return rows[0];
    } catch { /* local DB unavailable, fall through to Supabase */ }
  }
  // Fallback: Supabase (synced subset)
  const { data } = await supabase
    .from('user_profile')
    .select('id, display_name, role, local_email, local_password_hash')
    .eq('local_email', normalizedEmail)
    .maybeSingle();
  return data ?? null;
}

// POST /api/auth/local-login
router.post('/local-login', async (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) return res.status(400).json({ error: 'Email and password required' });

  try {
    const bcrypt = require('bcryptjs');
    const getSupabase = require('../supabase');
    const supabase = getSupabase();
    const normalizedEmail = email.toLowerCase().trim();

    // ── 1. Try user_profile (local DB first, Supabase fallback) ──────────────
    const profile = await findUserProfile(normalizedEmail, supabase);

    if (profile) {
      const valid = await bcrypt.compare(password, profile.local_password_hash);
      if (!valid) return res.status(401).json({ error: 'Invalid email or password' });

      // Find owner_id from local DB or Supabase owner_table
      const ownerId = await findOwnerId(profile.display_name, supabase);

      // If matched as an owner → pet owner dashboard; otherwise keep original role
      const role = ownerId ? 'pet_owner' : (profile.role === 'ADMIN' ? 'veterinarian' : 'pet_owner');
      return await generateSession(supabase, profile.local_email, profile.display_name, role, ownerId, password, res);
    }

    // ── 2. Try user_table (pet owners — email + password/hash generated by local system) ──
    const { data: petUser } = await supabase
      .from('user_table')
      .select('user_id, owner_id, email, password, password_hash, display_name')
      .eq('email', normalizedEmail)
      .maybeSingle();

    if (petUser) {
      let valid = false;
      if (petUser.password_hash) {
        try { valid = await bcrypt.compare(password, petUser.password_hash); } catch { valid = false; }
      }
      if (!valid && petUser.password) {
        valid = password === petUser.password;
      }
      if (!valid) return res.status(401).json({ error: 'Invalid email or password' });

      let displayName = petUser.display_name || '';
      if (!displayName && petUser.owner_id) {
        const { data: owner } = await supabase
          .from('owner_table')
          .select('owner_name')
          .eq('owner_id', petUser.owner_id)
          .maybeSingle();
        displayName = owner?.owner_name ?? '';
      }
      return await generateSession(supabase, petUser.email, displayName, 'pet_owner', petUser.owner_id, password, res);
    }

    // ── 3. Try owner_table directly using contact_number as login ────────────
    const { data: owner } = await supabase
      .from('owner_table')
      .select('owner_id, owner_name, contact_number')
      .eq('contact_number', normalizedEmail)
      .is('deleted_at', null)
      .maybeSingle();

    if (!owner) {
      return res.status(401).json({ error: 'Invalid email or password' });
    }

    // Password must match the contact number (default generated credential)
    if (password !== owner.contact_number) {
      return res.status(401).json({ error: 'Invalid email or password' });
    }

    // Use contact_number as the email for the Supabase session
    const ownerEmail = `${owner.contact_number}@digivet.lipa.ph`;
    return await generateSession(supabase, ownerEmail, owner.owner_name, 'pet_owner', owner.owner_id, password, res);

  } catch (err) {
    console.error('local-login error:', err);
    res.status(500).json({ error: 'Server error' });
  }
});

async function generateSession(supabase, email, displayName, role, ownerId, password, res) {
  const metadata = { full_name: displayName, role };
  if (ownerId) metadata.owner_id = ownerId;

  // upsertSupabaseUser: tries createUser first, updates on conflict — no listUsers() needed
  const { upsertSupabaseUser } = require('./authHelpers');
  await upsertSupabaseUser(supabase, email, password, metadata);

  return res.json({ email, role });
}

// POST /api/auth/register-owner
// Creates a Supabase account for a pet owner using their email from owner_table
router.post('/register-owner', async (req, res) => {
  const { email } = req.body;
  if (!email) return res.status(400).json({ error: 'Email is required' });

  try {
    const getSupabase = require('../supabase');
    const supabase = getSupabase();

    // Verify email exists in owner_table
    const { data: owner } = await supabase
      .from('owner_table')
      .select('owner_id, owner_name, email')
      .eq('email', email.toLowerCase().trim())
      .is('deleted_at', null)
      .maybeSingle();

    if (!owner) {
      return res.status(404).json({ error: 'This email is not registered in our system. Please contact the Lipa City Veterinary Office.' });
    }

    // Check if a Supabase account already exists for this email
    const { data: existing } = await supabase.auth.admin.listUsers();
    const alreadyExists = existing?.users?.some(u => u.email?.toLowerCase() === email.toLowerCase().trim());
    if (alreadyExists) {
      return res.status(409).json({ error: 'An account already exists for this email. Please sign in.' });
    }

    const { generatePassword } = require('./authHelpers');
    const password = generatePassword();

    const { error: createError } = await supabase.auth.admin.createUser({
      email: email.toLowerCase().trim(),
      password,
      email_confirm: true,
      user_metadata: { full_name: owner.owner_name, role: 'pet_owner', owner_id: owner.owner_id },
    });

    if (createError) return res.status(500).json({ error: 'Failed to create account: ' + createError.message });

    res.json({ success: true, owner_name: owner.owner_name, password });
  } catch (err) {
    res.status(500).json({ error: 'Server error' });
  }
});

// POST /api/auth/verify-owner
// Checks contact_number against owner_table
router.post('/verify-owner', async (req, res) => {
  const { contact_number } = req.body;
  if (!contact_number) return res.status(400).json({ error: 'Contact number required' });

  try {
    const getSupabase = require('../supabase');
    const supabase = getSupabase();

    const { data, error } = await supabase
      .from('owner_table')
      .select('owner_id, owner_name, qr_token, auth_email')
      .eq('contact_number', contact_number.trim())
      .is('deleted_at', null)
      .single();

    if (error || !data) {
      return res.status(404).json({ found: false });
    }

    if (data.auth_email) {
      return res.status(409).json({ error: 'An account is already linked to this contact number. Please sign in instead.' });
    }

    res.json({
      found: true,
      owner_id: data.owner_id,
      owner_name: data.owner_name,
      qr_token: data.qr_token,
    });
  } catch (err) {
    res.status(500).json({ error: 'Server error' });
  }
});

// POST /api/auth/link-account
// Links a Supabase auth email to the owner_table record after signup
router.post('/link-account', async (req, res) => {
  const { qr_token, email } = req.body;
  if (!qr_token || !email) return res.status(400).json({ error: 'qr_token and email required' });

  try {
    const getSupabase = require('../supabase');
    const supabase = getSupabase();

    const { error } = await supabase
      .from('owner_table')
      .update({ auth_email: email })
      .eq('qr_token', qr_token);

    if (error) return res.status(500).json({ error: 'Failed to link account' });
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: 'Server error' });
  }
});

// POST /api/auth/qr-login
// Validates a QR token from owner_table and returns a magic-link session
router.post('/qr-login', async (req, res) => {
  const { qr_token } = req.body;
  if (!qr_token) return res.status(400).json({ error: 'QR token required' });

  try {
    const getSupabase = require('../supabase');
    const supabase = getSupabase();

    const { data: owner, error } = await supabase
      .from('owner_table')
      .select('owner_name, auth_email')
      .eq('qr_token', qr_token.trim())
      .is('deleted_at', null)
      .single();

    if (error || !owner) {
      return res.status(404).json({ error: 'QR code not recognized. Please visit the Lipa City Veterinary Office.' });
    }

    if (!owner.auth_email) {
      return res.status(403).json({ error: 'No account linked to this QR code. Please register first.' });
    }

    const { data: linkData, error: linkError } = await supabase.auth.admin.generateLink({
      type: 'magiclink',
      email: owner.auth_email,
    });

    if (linkError) return res.status(500).json({ error: 'Failed to generate session' });

    res.json({
      email: owner.auth_email,
      token: linkData.properties.hashed_token,
    });
  } catch (err) {
    res.status(500).json({ error: 'Server error' });
  }
});

// POST /api/auth/send-owner-credentials
// Generates credentials for a pet owner and emails them
router.post('/send-owner-credentials', requireAuth, async (req, res) => {
  const { owner_id } = req.body;
  if (!owner_id) return res.status(400).json({ error: 'owner_id required' });

  try {
    const getSupabase = require('../supabase');
    const supabase = getSupabase();

    // Get owner details including credentials_sent status
    const { data: owner, error: ownerErr } = await supabase
      .from('owner_table')
      .select('owner_id, owner_name, email, credentials_sent')
      .eq('owner_id', owner_id)
      .is('deleted_at', null)
      .maybeSingle();

    if (ownerErr || !owner) return res.status(404).json({ error: 'Owner not found' });
    if (!owner.email)       return res.status(400).json({ error: 'This owner has no email address on record' });

    // Block resending unless explicitly forced
    const { force } = req.body;
    if (owner.credentials_sent && !force) {
      return res.status(409).json({
        error: 'Credentials already sent to this owner.',
        alreadySent: true,
      });
    }

    const { generatePassword } = require('./authHelpers');
    const password   = generatePassword();
    const email      = owner.email.toLowerCase();
    const metadata   = { full_name: owner.owner_name, role: 'pet_owner', owner_id: owner.owner_id };
    const redirectTo = `${process.env.CLIENT_URL}/welcome`;

    // Store password so Welcome page can retrieve it after the user confirms
    await supabase.from('owner_table')
      .update({ pending_password: password })
      .eq('owner_id', owner.owner_id);

    // If user already exists in Supabase auth, delete them first so we can recreate cleanly
    const { data: existing } = await supabase.auth.admin.listUsers();
    const existingUser = existing?.users?.find(u => u.email?.toLowerCase() === email);
    if (existingUser) await supabase.auth.admin.deleteUser(existingUser.id);

    // createUser with email_confirm: false → Supabase sends the confirmation email automatically
    // Password is set at creation so login works immediately after confirmation
    const { error: createErr } = await supabase.auth.admin.createUser({
      email,
      password,
      email_confirm: false,
      email_redirect_to: redirectTo,
      user_metadata: { ...metadata, plain_password: password },
    });

    if (createErr) throw new Error(createErr.message);

    await supabase.from('owner_table')
      .update({ credentials_sent: true })
      .eq('owner_id', owner.owner_id);

    res.json({ success: true, message: `Credentials email sent to ${email}` });
  } catch (err) {
    console.error('send-owner-credentials error:', err);
    res.status(500).json({ error: err.message || 'Server error' });
  }
});


// POST /api/auth/set-owner-role
// Called after OTP login when user has no role — looks up owner by email and sets pet_owner role
router.post('/set-owner-role', async (req, res) => {
  const { email } = req.body;
  if (!email) return res.status(400).json({ error: 'Email required' });

  try {
    const getSupabase = require('../supabase');
    const supabase = getSupabase();
    const normalizedEmail = email.toLowerCase().trim();

    // Find the profile in local DB or Supabase
    const profile = await findUserProfile(normalizedEmail, supabase);
    const displayName = profile?.display_name ?? '';

    // Find owner_id
    const ownerId = await findOwnerId(displayName, supabase);

    // Find the Supabase auth user and update their metadata
    const { data: listData } = await supabase.auth.admin.listUsers();
    const authUser = listData?.users?.find(u => u.email?.toLowerCase() === normalizedEmail);

    if (authUser) {
      await supabase.auth.admin.updateUserById(authUser.id, {
        email_confirm: true,
        user_metadata: { full_name: displayName, role: 'pet_owner', owner_id: ownerId },
      });
    }

    res.json({ success: true, role: 'pet_owner', owner_id: ownerId });
  } catch (err) {
    res.status(500).json({ error: 'Server error' });
  }
});

// Helper: find owner_id from local DB first, then Supabase
async function findOwnerId(displayName, supabase) {
  if (!displayName) return null;

  if (process.env.LOCAL_DATABASE_URL) {
    try {
      const { Pool } = require('pg');
      const pool = new Pool({ connectionString: process.env.LOCAL_DATABASE_URL, connectionTimeoutMillis: 3000 });
      const { rows } = await pool.query(
        'SELECT owner_id FROM owner_table WHERE LOWER(owner_name) = LOWER($1) AND deleted_at IS NULL LIMIT 1',
        [displayName.trim()]
      );
      await pool.end();
      if (rows.length > 0) return rows[0].owner_id;
    } catch { /* fall through */ }
  }

  const { data } = await supabase
    .from('owner_table')
    .select('owner_id')
    .ilike('owner_name', displayName.trim())
    .is('deleted_at', null)
    .maybeSingle();
  return data?.owner_id ?? null;
}

// GET /api/auth/my-credentials
// Called by the Welcome page after Supabase auth is established.
// Returns the pending plaintext password for the authenticated owner, then clears it.
router.get('/my-credentials', requireAuth, async (req, res) => {
  try {
    const getSupabase = require('../supabase');
    const supabase    = getSupabase();
    const userEmail   = req.user.email?.toLowerCase();

    const { data: owner, error } = await supabase
      .from('owner_table')
      .select('owner_id, owner_name, email, pending_password')
      .eq('email', userEmail)
      .is('deleted_at', null)
      .maybeSingle();

    if (error || !owner || !owner.pending_password) {
      return res.status(404).json({ error: 'No pending credentials found.' });
    }

    // Clear it immediately — one-time retrieval
    await supabase.from('owner_table')
      .update({ pending_password: null })
      .eq('owner_id', owner.owner_id);

    res.json({
      name:     owner.owner_name,
      email:    owner.email,
      password: owner.pending_password,
    });
  } catch (err) {
    res.status(500).json({ error: 'Server error' });
  }
});

module.exports = router;